(MAKE-TEST-GROUP 'ADD-FUNCTION (LAMBDA () 
	(MAKE-TEST '-CAN-ADD-TWO-NUMBER
		(LAMBDA ()
		  (LET ((Y (ADD 5 5)))
		    (ASSERT-EQUAL Y 10))))
	(MAKE-TEST '-CAN-AGIN-ADD-TWO-NUMBER
	   (LAMBDA ()
		  (LET ((Y (ADD 5 5)))
		    (ASSERT-EQUAL (cons 1 3) (cons 1 3) ))))))
(quit)
